/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

double tanh_approx(double);
Vec dense_layer(Vec *, Vec *, Vec *, int, int, int, Arena *);
Vec mlp_forward3(Vec *, Vec *, Vec *, Vec *, Vec *, Vec *, Vec *, int, int, int, int, Arena *);
double heuristic_prior(int, int, int, int);
double blend(double, double, double, double);
double mask_score(double, int);
int pick5(double, double, double, double, double);

double tanh_approx(double x __attribute__((unused))) {
    if ((x >= 5.0)) {
    return 1.0;
    } else {
    if ((x <= -5.0)) {
    return -1.0;
    } else {
    double x2 __attribute__((unused)) = (x * x);
    double x4 __attribute__((unused)) = (x2 * x2);
    double x6 __attribute__((unused)) = (x4 * x2);
    return ((x * (135135.0 + ((17325.0 * x2) + ((378.0 * x4) + x6)))) / (135135.0 + ((62370.0 * x2) + ((3150.0 * x4) + (28.0 * x6)))));
    }
    }
}

Vec dense_layer(Vec * w __attribute__((unused)), Vec * b __attribute__((unused)), Vec * x __attribute__((unused)), int n_in __attribute__((unused)), int n_out __attribute__((unused)), int act __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec out __attribute__((unused)) = vec_new(dest);
    void * __loop_result_0 __attribute__((unused));
    double row = 0;
    while (1) {
        if ((row < n_out)) {
    double __let_val_0 __attribute__((unused));
    int i = 0;
    double acc = (*((double *)(vec_get(b, row))));
    while (1) {
        if ((i < n_in)) {
        int __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (acc + ((*((double *)(vec_get(w, ((row * n_in) + i))))) * (*((double *)(vec_get(x, i))))));
        i = __recur_tmp_0;
        acc = __recur_tmp_1;
        continue;
        } else {
        __let_val_0 = acc;
        break;
        }
    }
    double s __attribute__((unused)) = __let_val_0;
    (void)(vec_push_(&(out), vec_box_f64(&(out), ((act == 1) ? tanh_approx(s) : s))));
        double __recur_tmp_0 = (row + 1);
        row = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return out;
}

Vec mlp_forward3(Vec * w0 __attribute__((unused)), Vec * b0 __attribute__((unused)), Vec * w1 __attribute__((unused)), Vec * b1 __attribute__((unused)), Vec * w2 __attribute__((unused)), Vec * b2 __attribute__((unused)), Vec * x __attribute__((unused)), int n0 __attribute__((unused)), int n1 __attribute__((unused)), int n2 __attribute__((unused)), int n3 __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec h1 __attribute__((unused)) = dense_layer(w0, b0, x, n0, n1, 1, dest);
    Vec h2 __attribute__((unused)) = dense_layer(w1, b1, &(h1), n1, n2, 1, dest);
    return dense_layer(w2, b2, &(h2), n2, n3, 0, dest);
}

double heuristic_prior(int arch __attribute__((unused)), int card __attribute__((unused)), int last_kind __attribute__((unused)), int bank __attribute__((unused))) {
    if ((card < 0)) {
    if (((arch == 0) && (bank == 1))) {
    return 3.0;
    } else {
    return 0.0;
    }
    } else {
    if ((arch == 0)) {
    if ((card_kind(card) == 0)) {
    return (2.0 + (0.01 * card_power(card)));
    } else {
    return (1.0 + (0.01 * card_power(card)));
    }
    } else {
    if ((arch == 1)) {
    if ((card_kind(card) == 1)) {
    return (3.0 + (0.01 * card_power(card)));
    } else {
    if ((card_kind(card) == 2)) {
    return (2.0 + (0.01 * card_power(card)));
    } else {
    return (1.0 + (0.01 * card_power(card)));
    }
    }
    } else {
    if (((last_kind >= 0) && kind_beats(card_kind(card), last_kind))) {
    return (3.0 + (0.01 * card_power(card)));
    } else {
    return (1.0 + (0.01 * card_power(card)));
    }
    }
    }
    }
}

double blend(double prior __attribute__((unused)), double logit __attribute__((unused)), double w_h __attribute__((unused)), double w_n __attribute__((unused))) {
    return ((w_h * prior) + (w_n * logit));
}

double mask_score(double s __attribute__((unused)), int legal __attribute__((unused))) {
    if ((legal == 1)) {
    return s;
    } else {
    return -1000000.0;
    }
}

int pick5(double m0 __attribute__((unused)), double m1 __attribute__((unused)), double m2 __attribute__((unused)), double m3 __attribute__((unused)), double mp __attribute__((unused))) {
    int a __attribute__((unused)) = ((m0 >= m1) ? 0 : 1);
    double ma __attribute__((unused)) = ((m0 >= m1) ? m0 : m1);
    int b __attribute__((unused)) = ((m2 >= m3) ? 2 : 3);
    double mb __attribute__((unused)) = ((m2 >= m3) ? m2 : m3);
    int c __attribute__((unused)) = ((ma >= mb) ? a : b);
    double mc __attribute__((unused)) = ((ma >= mb) ? ma : mb);
    if ((mc >= mp)) {
    return c;
    } else {
    return -1;
    }
}

