/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int start_hull();
int start_energy();
int max_rounds();
int hand_size();
int num_cards();
int energy_cap(int);
int card_kind(int);
int card_tier(int);
int card_cost(int);
int card_power(int);
int kind_beats(int, int);
int is_legal_play(int, int);
int damage_dealt(int, int);
int round_start_energy(int);
int energy_after_play(int, int);
int round_winner_by_hull(int, int);
int match_decided(int, int);

int start_hull(void) {
    return 20;
}

int start_energy(void) {
    return 2;
}

int max_rounds(void) {
    return 8;
}

int hand_size(void) {
    return 4;
}

int num_cards(void) {
    return 9;
}

int energy_cap(int e __attribute__((unused))) {
    if ((e > 6)) {
    return 6;
    } else {
    return e;
    }
}

int card_kind(int id __attribute__((unused))) {
    return (id / 3);
}

int card_tier(int id __attribute__((unused))) {
    return (id - ((id / 3) * 3));
}

int card_cost(int id __attribute__((unused))) {
    if ((card_tier(id) == 0)) {
    return 1;
    } else {
    if ((card_tier(id) == 1)) {
    return 2;
    } else {
    return 4;
    }
    }
}

int card_power(int id __attribute__((unused))) {
    if ((card_tier(id) == 0)) {
    return 3;
    } else {
    if ((card_tier(id) == 1)) {
    return 6;
    } else {
    return 10;
    }
    }
}

int kind_beats(int a __attribute__((unused)), int b __attribute__((unused))) {
    return (b == ((a == 2) ? 0 : (a + 1)));
}

int is_legal_play(int id __attribute__((unused)), int energy __attribute__((unused))) {
    return ((id >= 0) && ((id <= 8) && (card_cost(id) <= energy)));
}

int damage_dealt(int a __attribute__((unused)), int b __attribute__((unused))) {
    if ((a < 0)) {
    return 0;
    } else {
    if ((b < 0)) {
    if ((card_kind(a) == 2)) {
    return 0;
    } else {
    return card_power(a);
    }
    } else {
    if ((card_kind(a) == card_kind(b))) {
    if ((card_kind(a) == 0)) {
    return card_power(a);
    } else {
    if ((card_kind(a) == 1)) {
    return (card_power(a) / 2);
    } else {
    return 0;
    }
    }
    } else {
    if (kind_beats(card_kind(a), card_kind(b))) {
    return card_power(a);
    } else {
    return 0;
    }
    }
    }
    }
}

int round_start_energy(int e __attribute__((unused))) {
    return energy_cap((e + 2));
}

int energy_after_play(int e __attribute__((unused)), int played __attribute__((unused))) {
    if ((played < 0)) {
    return energy_cap((e + 1));
    } else {
    return (e - card_cost(played));
    }
}

int round_winner_by_hull(int h0 __attribute__((unused)), int h1 __attribute__((unused))) {
    if ((h0 > h1)) {
    return 0;
    } else {
    if ((h0 < h1)) {
    return 1;
    } else {
    return 2;
    }
    }
}

int match_decided(int h0 __attribute__((unused)), int h1 __attribute__((unused))) {
    return ((h0 <= 0) || (h1 <= 0));
}

