#include "card_text.h"

/* Display names and one-line rules text for the 105-card catalog (clients only; all NUMBERS live in card_rules.prn).
 * Operations cards start their text with their keyword (Lock / Sabotage / Flank / Scan / Siphon). The Java and WOTAN
 * copies are generated from this table: scripts/gen_rules.sh (CardText.java) and scripts/export_cards.sh (cards.json). */
#define DW_CARD_COUNT 105

typedef struct { const char *name, *text; } CardEntry;

static const CardEntry CARDS[DW_CARD_COUNT] = {
    {"Spark", ""},
    {"Bolt", ""},
    {"Railgun", ""},
    {"Sidewinder", "Flank: +1 against Defense."},
    {"Interceptor", "Flank: +2 against Defense."},
    {"Stormwing", "Flank: +3 against Defense."},
    {"Buckler", ""},
    {"Barrier", ""},
    {"Bastion", ""},
    {"Call Option", "If it lands: +1 energy."},
    {"Overclock", "You take 4."},
    {"Infinity Edge", "Lock: 4 always lands and it can't be reflected."},
    {"Rageblade", "+1 damage per 2 rounds played."},
    {"Kraken Slayer", "Costs 2 credits. Every 3rd round: +6 unblockable."},
    {"Statikk Shiv", "+3 against Operations."},
    {"Liandry's Torment", "Sabotage: if it lands, opp burns 2 for 3 rounds."},
    {"Death Mark", "Scan: +8 if opp hull is 10 or less."},
    {"Final Spark", "You take 4."},
    {"Short Squeeze", "Scan: +1 per energy opp holds."},
    {"Margin Call", "Scan: +8 if opp has no credits."},
    {"Pump & Dump", "You take 6."},
    {"Flash Crash", "Siphon: opp loses 2 credits. All damage halved."},
    {"Yolo Roll", "50%: +9 damage. Else you take 3."},
    {"Quick Draw", "Flank: +4 if opp passed."},
    {"Glass Cannon", "If you're hit, take 5 more."},
    {"Piercing Round", "Lock: ignores armor."},
    {"Executioner", "Scan: +8 if opp hull is 8 or less."},
    {"Hail Mary", "+11 if your hull is 6 or less."},
    {"Iron Dwarf", "+2 damage."},
    {"Pressure", "Siphon: if it lands, opp loses 1 energy."},
    {"Bribe", "Costs 2 credits."},
    {"Yield Contract", "3+ energy left: +1 energy."},
    {"Thornmail", "Reflects half the damage you take."},
    {"Heartsteel", "Gain armor equal to half damage taken."},
    {"Dark Pool", "Sabotage: becomes a mystery exotic."},
    {"Naked Short", "+3 energy. If hit, take 5 more."},
    {"Hostile Takeover", "Sabotage: cancel opp's card and play it yourself."},
    {"Corporate Espionage", "Scan: opp takes 2x their card's cost, unblockable."},
    {"Synthetic Short", "+3 energy if nobody is hurt."},
    {"Xeno-Biomass", "Heal 2 per round for 4 rounds."},
    {"Sunfire Aegis", "Sabotage: opp burns 1 per round for 5 rounds."},
    {"Quartermaster", "+1 energy."},
    {"Field Cleric", "Heal 2."},
    {"Capacitor", "Gain 2 energy."},
    {"Dividend Stock", "+2 credits."},
    {"Bailout Loan", "+4 energy, -4 credits."},
    {"Volatility", "Siphon: opp loses 3 credits."},
    {"Merkle Blindness", "Hide your meters for 3 rounds."},
    {"Corrosion", "Sabotage: disable 1 of opp's cards next round."},
    {"Fire Sale", "Redraw your hand. +2 credits."},
    {"Total Blackout", "Siphon: cancel opp's card and drain all their energy."},
    {"Realm Warp", "Scan: costs 3 credits. Swap hands."},
    {"Put Option", "Heal up to 3 of the damage you take."},
    {"Stasis Frame", "Immune if your hull is 6 or less."},
    {"Underwrite", "+1 energy. If hit for 6+, take 4 more."},
    {"Parametric Policy", "Heal 4 if your hull is 8 or less."},
    {"Replacement Cost", "If hit: +3 armor."},
    {"Credit Default Swap", "Stops an Offense card: +2 energy, +1 credit."},
    {"Reinsurance Bundle", "Immune this round. Next round -2 energy."},
    {"Immortal Aegisbow", "Costs 2 credits. Survive lethal at 1."},
    {"Zhonya's Hourglass", "Immune this round. Next round -1 energy."},
    {"Seraph's Embrace", "+4 armor."},
    {"Dead Squares", "+2 armor."},
    {"Aegis Defender", "+2 armor."},
    {"Monsoon", "Reflect all damage taken. Clear burn."},
    {"Wish", "Heal 6."},
    {"Bailout Package", "Heal 8. Erase your debt."},
    {"Cold Steel", "Siphon: opp played cost 3+: they lose 2 energy."},
    {"Mana Ward", "Convert up to 4 energy to armor."},
    {"Corporate Merger", "Both hulls become the average."},
    {"Glacial Prison", "Sabotage: disable 2 of opp's cards next round."},
    {"Chronobreak", "Restore hull to last round's start."},
    {"Hush Money", "Siphon: +2 credits, opp loses 2."},
    {"Targeting Laser", "Lock: ignores armor."},
    {"Bunker Buster", "Lock: +4 against Defense."},
    {"Phase Lance", "Lock: ignores armor. 3 always lands."},
    {"Heat Seeker", "Lock: +3 if opp played cost 3+."},
    {"Sniper Uplink", "Lock: ignores armor. +5 if opp hull is 10 or less."},
    {"Blindside", "Flank: +5 if opp passed. +2 against Defense."},
    {"Orbital Slingshot", "Flank: 4 always lands."},
    {"Drift Strike", "Flank: +6 against Defense."},
    {"Threat Assessment", "Scan: +2 per point of opp's card cost."},
    {"Logic Bomb", "Sabotage: if it lands, opp burns 3 for 2 rounds."},
    {"Power Tap", "Siphon: if it lands, opp loses 2 energy and you gain 2."},
    {"Point Defense Grid", "+3 armor. Reflects 30% of the damage you take."},
    {"Missile Salvo", "+1 damage per energy you have left."},
    {"Cluster Bomb", "If it lands: +3 unblockable."},
    {"Hellfire Rack", "If it lands: +4 unblockable."},
    {"Mass Driver", "You take 2."},
    {"Recoil Cannon", "You take 3."},
    {"Ripple Fire", "+3 if opp played a card."},
    {"Salvage Rounds", "If it lands: +1 credit."},
    {"Overwatch Strike", "+3 if opp holds 4+ energy."},
    {"Extinction Salvo", "If it lands: +6 unblockable."},
    {"Ricochet", "40%: +7 damage. Else +1."},
    {"Sponsored Barrage", "+1 per 2 credits you hold."},
    {"Capacitor Discharge", "+4 if you have 3+ energy left."},
    {"Gatling Rounds", "Every 2nd round: +4."},
    {"Ion Cannon", "+1 energy."},
    {"Tungsten Rod", "+4 against Operations."},
    {"Doomsday Warhead", "Costs 3 credits. If it lands: +8."},
    {"Broadside", "If you're hit, take 3 more."},
    {"Dud Round", "50%: +5 damage."},
    {"Volley Fire", "+3 if opp passed."},
    {"Fusion Torch", "You take 1."},
};

const char *dw_card_name(int id) { return id == -1 ? "PASS" : (id >= 0 && id < DW_CARD_COUNT) ? CARDS[id].name : "?"; }
const char *dw_card_text(int id) { return (id >= 0 && id < DW_CARD_COUNT) ? CARDS[id].text : ""; }
const char *dw_kind_name(int kind) { return kind == 0 ? "Offense" : kind == 1 ? "Operations" : kind == 2 ? "Defense" : "?"; }
const char *dw_keyword_name(int kw) {
    static const char *const K[6] = {"", "Lock", "Sabotage", "Flank", "Scan", "Siphon"};
    return kw >= 0 && kw < 6 ? K[kw] : "";
}
