/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int fx_card_id(int, int, int);
int fx_kind_of(int);
int fx_scenario(int, int, int, int);
int fx_winner_seat(int, int, int, int);
int fx_is_crit(int, int, int, int, int);
int fx_clash_duration_ms(int, int);
int fx_clash_cue(int, int, int);
int fx_clash0();
int fx_clash1(int);
int fx_hull0(int);
int fx_hull1(int, int);
int fx_armor0(int, int);
int fx_armor1(int, int, int);
int fx_econ0(int, int, int);
int fx_econ1(int, int, int, int);
int fx_stat0(int, int, int, int);
int fx_stat1(int, int, int, int, int);
int fx_settle0(int, int, int, int, int);
int fx_timeline_total_ms(int, int, int, int, int);
int min_i32(int, int);
int fx_has_hull(int, int, int, int);
int fx_has_armor(int, int, int, int);
int fx_has_econ(int, int, int, int);
int fx_has_stat(int, int, int, int, int);

int fx_card_id(int eff __attribute__((unused)), int declared __attribute__((unused)), int cancelled __attribute__((unused))) {
    if ((eff >= 0)) {
    return eff;
    } else {
    if ((cancelled == 1)) {
    return declared;
    } else {
    return -1;
    }
    }
}

int fx_kind_of(int id __attribute__((unused))) {
    if ((id < 0)) {
    return -1;
    } else {
    return card_kind(id);
    }
}

int fx_scenario(int kind_a __attribute__((unused)), int kind_b __attribute__((unused)), int cancelled_a __attribute__((unused)), int cancelled_b __attribute__((unused))) {
    if (((cancelled_a == 1) || (cancelled_b == 1))) {
    return 10;
    } else {
    if (((kind_a < 0) && (kind_b < 0))) {
    return 9;
    } else {
    if (((kind_a < 0) || (kind_b < 0))) {
    if ((((kind_a >= 0) ? kind_a : kind_b) == 2)) {
    return 8;
    } else {
    return 7;
    }
    } else {
    if ((kind_a == kind_b)) {
    if ((kind_a == 0)) {
    return 4;
    } else {
    if ((kind_a == 1)) {
    return 5;
    } else {
    return 6;
    }
    }
    } else {
    if (kind_beats(kind_a, kind_b)) {
    if ((kind_a == 0)) {
    return 1;
    } else {
    if ((kind_a == 2)) {
    return 2;
    } else {
    return 3;
    }
    }
    } else {
    if ((kind_b == 0)) {
    return 1;
    } else {
    if ((kind_b == 2)) {
    return 2;
    } else {
    return 3;
    }
    }
    }
    }
    }
    }
    }
}

int fx_winner_seat(int kind_a __attribute__((unused)), int kind_b __attribute__((unused)), int cancelled_a __attribute__((unused)), int cancelled_b __attribute__((unused))) {
    if (((cancelled_a == 1) || (cancelled_b == 1))) {
    return -1;
    } else {
    if (((kind_a < 0) && (kind_b < 0))) {
    return -1;
    } else {
    if ((kind_a < 0)) {
    return 1;
    } else {
    if ((kind_b < 0)) {
    return 0;
    } else {
    if ((kind_a == kind_b)) {
    return -1;
    } else {
    if (kind_beats(kind_a, kind_b)) {
    return 0;
    } else {
    return 1;
    }
    }
    }
    }
    }
    }
}

int fx_is_crit(int scenario __attribute__((unused)), int dmg_lose __attribute__((unused)), int power_win __attribute__((unused)), int power_lose __attribute__((unused)), int cost_win __attribute__((unused))) {
    if ((scenario == 1)) {
    return (dmg_lose >= 8);
    } else {
    if ((scenario == 2)) {
    return ((power_win - power_lose) >= 3);
    } else {
    if ((scenario == 3)) {
    return ((dmg_lose >= 8) || (cost_win >= 5));
    } else {
    return 0;
    }
    }
    }
}

int fx_clash_duration_ms(int scenario __attribute__((unused)), int crit __attribute__((unused))) {
    if ((scenario == 1)) {
    if (crit) {
    return 1900;
    } else {
    return 1500;
    }
    } else {
    if ((scenario == 2)) {
    if (crit) {
    return 2000;
    } else {
    return 1700;
    }
    } else {
    if ((scenario == 3)) {
    if (crit) {
    return 2200;
    } else {
    return 2000;
    }
    } else {
    if ((scenario == 4)) {
    return 1400;
    } else {
    if ((scenario == 5)) {
    return 1400;
    } else {
    if ((scenario == 6)) {
    return 1400;
    } else {
    if ((scenario == 7)) {
    return 1200;
    } else {
    if ((scenario == 8)) {
    return 1000;
    } else {
    if ((scenario == 9)) {
    return 700;
    } else {
    if ((scenario == 10)) {
    return 1100;
    } else {
    return 1400;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
}

int fx_clash_cue(int scenario __attribute__((unused)), int crit __attribute__((unused)), int kw __attribute__((unused))) {
    if ((scenario == 1)) {
    if (crit) {
    return 1;
    } else {
    return 0;
    }
    } else {
    if ((scenario == 2)) {
    if (crit) {
    return 3;
    } else {
    return 2;
    }
    } else {
    if ((scenario == 3)) {
    if (crit) {
    return 9;
    } else {
    if ((kw == 1)) {
    return 4;
    } else {
    if ((kw == 2)) {
    return 5;
    } else {
    if ((kw == 3)) {
    return 6;
    } else {
    if ((kw == 4)) {
    return 7;
    } else {
    return 8;
    }
    }
    }
    }
    }
    } else {
    if ((scenario == 4)) {
    return 10;
    } else {
    if ((scenario == 5)) {
    return 11;
    } else {
    if ((scenario == 6)) {
    return 12;
    } else {
    if ((scenario == 7)) {
    return 13;
    } else {
    if ((scenario == 8)) {
    return 16;
    } else {
    if ((scenario == 9)) {
    return 14;
    } else {
    if ((scenario == 10)) {
    return 15;
    } else {
    return 14;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
}

int fx_clash0(void) {
    return 600;
}

int fx_clash1(int clash_dur __attribute__((unused))) {
    return (fx_clash0() + clash_dur);
}

int fx_hull0(int clash_dur __attribute__((unused))) {
    return (fx_clash1(clash_dur) + 220);
}

int fx_hull1(int clash_dur __attribute__((unused)), int has_hull __attribute__((unused))) {
    return (fx_hull0(clash_dur) + (has_hull * 950));
}

int fx_armor0(int clash_dur __attribute__((unused)), int has_hull __attribute__((unused))) {
    return (fx_hull1(clash_dur, has_hull) + (has_hull * 120));
}

int fx_armor1(int clash_dur __attribute__((unused)), int has_hull __attribute__((unused)), int has_armor __attribute__((unused))) {
    return (fx_armor0(clash_dur, has_hull) + (has_armor * 850));
}

int fx_econ0(int clash_dur __attribute__((unused)), int has_hull __attribute__((unused)), int has_armor __attribute__((unused))) {
    return (fx_armor1(clash_dur, has_hull, has_armor) + (has_armor * 100));
}

int fx_econ1(int clash_dur __attribute__((unused)), int has_hull __attribute__((unused)), int has_armor __attribute__((unused)), int has_econ __attribute__((unused))) {
    return (fx_econ0(clash_dur, has_hull, has_armor) + (has_econ * 950));
}

int fx_stat0(int clash_dur __attribute__((unused)), int has_hull __attribute__((unused)), int has_armor __attribute__((unused)), int has_econ __attribute__((unused))) {
    return (fx_econ1(clash_dur, has_hull, has_armor, has_econ) + (has_econ * 100));
}

int fx_stat1(int clash_dur __attribute__((unused)), int has_hull __attribute__((unused)), int has_armor __attribute__((unused)), int has_econ __attribute__((unused)), int has_stat __attribute__((unused))) {
    return (fx_stat0(clash_dur, has_hull, has_armor, has_econ) + (has_stat * 750));
}

int fx_settle0(int clash_dur __attribute__((unused)), int has_hull __attribute__((unused)), int has_armor __attribute__((unused)), int has_econ __attribute__((unused)), int has_stat __attribute__((unused))) {
    return fx_stat1(clash_dur, has_hull, has_armor, has_econ, has_stat);
}

int fx_timeline_total_ms(int clash_dur __attribute__((unused)), int has_hull __attribute__((unused)), int has_armor __attribute__((unused)), int has_econ __attribute__((unused)), int has_stat __attribute__((unused))) {
    return min_i32((fx_settle0(clash_dur, has_hull, has_armor, has_econ, has_stat) + 320), 9000);
}

int min_i32(int a __attribute__((unused)), int b __attribute__((unused))) {
    if ((a < b)) {
    return a;
    } else {
    return b;
    }
}

int fx_has_hull(int dmg_you __attribute__((unused)), int dmg_opp __attribute__((unused)), int heal_you __attribute__((unused)), int heal_opp __attribute__((unused))) {
    return ((dmg_you > 0) || ((dmg_opp > 0) || ((heal_you > 0) || (heal_opp > 0))));
}

int fx_has_armor(int armor_before_you __attribute__((unused)), int armor_after_you __attribute__((unused)), int armor_before_opp __attribute__((unused)), int armor_after_opp __attribute__((unused))) {
    return ((!((armor_after_you == armor_before_you))) || (!((armor_after_opp == armor_before_opp))));
}

int fx_has_econ(int energy_delta_you __attribute__((unused)), int energy_delta_opp __attribute__((unused)), int vault_delta_you __attribute__((unused)), int vault_delta_opp __attribute__((unused))) {
    return ((!((energy_delta_you == 0))) || ((!((energy_delta_opp == 0))) || ((!((vault_delta_you == 0))) || (!((vault_delta_opp == 0))))));
}

int fx_has_stat(int new_status_you __attribute__((unused)), int new_status_opp __attribute__((unused)), int disabled_you __attribute__((unused)), int disabled_opp __attribute__((unused)), int swapped __attribute__((unused))) {
    return ((!((new_status_you == 0))) || ((!((new_status_opp == 0))) || ((!((disabled_you == 0))) || ((!((disabled_opp == 0))) || (!((swapped == 0)))))));
}

