#!/usr/bin/env python3
"""DEADWEIGHT hybrid bot brain -- Python side (S503-14b): independent reference forward pass, BPMW blob I/O, and
honest DISTILLATION of a hand-written expected-value teacher into the MLP. NOT RL-trained: the league (dw_train.py)
produces RL weights later; they drop in through the same blob format (BRAWLPIT's export_policy_weights.py layout).

Reference forward pass = the same math as PARENA/stdlib/deadweight/bot_brain.prn (58 -> H1 tanh -> H2 tanh -> 5
linear, tanh replaced by the pure-PARENA Lambert continued-fraction approximation, clamped to +-1 at |x|>=5), written
independently in plain Python doubles so tests/… parity catches an emitter or glue bug.

Usage:
  python3 training/dw_brain.py distill --out /tmp/w.bin [--emit-c core/brain_default.c] [--samples 60000 --epochs 60]
  python3 training/dw_brain.py info FILE
"""
import argparse
import math
import os
import random
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import dw_rules as R
import dw_env as E

MAGIC = b"BPMW"
OBS = E.OBS_DIM  # 58
ACT = 5


def tanh_approx(x):
    if x >= 5.0: return 1.0
    if x <= -5.0: return -1.0
    x2 = x * x; x4 = x2 * x2; x6 = x4 * x2
    return (x * (135135.0 + (17325.0 * x2 + (378.0 * x4 + x6)))) / (135135.0 + (62370.0 * x2 + (3150.0 * x4 + 28.0 * x6)))


def forward(layers, obs):
    """layers: [(W rows out x in, b, act)]; act 1 = tanh, 0 = linear."""
    x = list(obs)
    for W, b, act in layers:
        y = []
        for row, bias in zip(W, b):
            s = bias
            for wi, xi in zip(row, x): s += wi * xi
            y.append(tanh_approx(s) if act == 1 else s)
        x = y
    return x


def write_blob(path_or_none, layers):
    """layers as above (values quantised to float32 exactly as the C loader will read them). Returns bytes."""
    out = bytearray(MAGIC + struct.pack("<II", 1, len(layers)))
    for W, b, act in layers: out += struct.pack("<IIB", len(W[0]), len(W), act)
    for W, b, act in layers:
        for row in W: out += struct.pack("<%df" % len(row), *row)
        out += struct.pack("<%df" % len(b), *b)
    if path_or_none:
        with open(path_or_none, "wb") as f: f.write(out)
    return bytes(out)


def read_blob(data):
    if data[:4] != MAGIC: raise ValueError("bad magic")
    ver, n = struct.unpack_from("<II", data, 4)
    if ver != 1: raise ValueError("bad version")
    dims = []; cur = 12
    for _ in range(n):
        i, o, a = struct.unpack_from("<IIB", data, cur); cur += 9; dims.append((i, o, a))
    layers = []
    for i, o, a in dims:
        W = []
        for _ in range(o):
            W.append(list(struct.unpack_from("<%df" % i, data, cur))); cur += 4 * i
        b = list(struct.unpack_from("<%df" % o, data, cur)); cur += 4 * o
        layers.append((W, b, a))
    if cur != len(data): raise ValueError("trailing bytes")
    return layers


def emit_c(path, blob):
    with open(path, "w") as f:
        f.write("/* Generated by training/dw_brain.py distill --emit-c -- do not edit by hand.\n"
                " * DISTILLED from a hand-written expected-value teacher (NOT RL-trained). BPMW v1 blob, see core/brain.h. */\n")
        f.write("const unsigned char dw_brain_default_blob[] = {\n")
        for i in range(0, len(blob), 16): f.write("  " + ",".join("0x%02x" % c for c in blob[i:i + 16]) + ",\n")
        f.write("};\nconst unsigned int dw_brain_default_blob_len = %d;\n" % len(blob))


# ---------------------------------------------------------------- teacher + state sampling (distillation only)
def random_state(rng):
    hand = rng.sample(range(9), 4)
    for i in range(4):
        if rng.random() < 0.03: hand[i] = -1
    kinds = [rng.choice([0, 1, 2, 3, 0, 1, 2]) for _ in range(3)]
    return {"hull_you": rng.randint(1, 20), "hull_opp": rng.randint(1, 20), "energy_you": rng.randint(0, 6),
            "energy_opp": rng.randint(0, 6), "round": rng.randint(1, 8), "hand": hand,
            "opp_hand_size": rng.randint(1, 4)}, kinds


def teacher(rs, kinds):
    """Counter-EV: model the opponent as (p_repeat) repeating its last kind, else uniform, sometimes passing, playing the
    best tier its energy allows; score each action by expected (damage dealt - damage taken)/10, slightly favouring
    cheap plays and banking when energy is low. Returns 5 scores (slots 0-3, pass); illegal slots get None."""
    e = rs["energy_opp"]
    if e >= 4: tier = 2
    elif e >= 2: tier = 1
    else: tier = 0
    can_play = e >= 1
    last = kinds[2]
    pk = [1.0 / 3] * 3
    if last < 3:
        pk = [0.5 if k == last else 0.25 for k in range(3)]
    p_pass = 0.1 if can_play else 1.0
    scale = 1.0 - p_pass
    out = []
    for s in range(4):
        a = rs["hand"][s]
        if a < 0 or not R.is_legal_play(a, rs["energy_you"], rs.get("vault_you", R.START_VAULT)): out.append(None); continue
        v = p_pass * (R.damage_dealt(a, -1) - 0)
        for k in range(3):
            opp = k * 3 + tier
            v += scale * pk[k] * (R.damage_dealt(a, opp) - R.damage_dealt(opp, a))
        v -= 0.4 * R.card_cost(a)
        out.append(v / 10.0)
    v = 0.0
    for k in range(3):
        opp = k * 3 + tier
        v += scale * pk[k] * (0 - R.damage_dealt(opp, -1))
    v += 0.5 * (6 - rs["energy_you"]) / 6.0 * 1.0 + 0.4   # banking value: more when low on energy
    out.append(v / 10.0)
    return out


def build_dataset(n, seed):
    rng = random.Random(seed)
    X, Y, M = [], [], []
    for _ in range(n):
        rs, kinds = random_state(rng)
        t = teacher(rs, kinds)
        X.append(E.build_observation(rs, kinds))
        Y.append([0.0 if v is None else v for v in t]); M.append([0.0 if v is None else 1.0 for v in t])
    return X, Y, M


def distill(samples, epochs, hidden, seed, lr=3e-3):
    import numpy as np
    X, Y, M = (np.array(a, dtype=np.float64) for a in build_dataset(samples, seed))
    rng = np.random.default_rng(seed)
    sizes = [OBS, hidden, hidden, ACT]
    Ws = [rng.normal(0, math.sqrt(1.0 / sizes[i]), (sizes[i + 1], sizes[i])) for i in range(3)]
    bs = [np.zeros(sizes[i + 1]) for i in range(3)]
    mW = [np.zeros_like(w) for w in Ws]; vW = [np.zeros_like(w) for w in Ws]
    mb = [np.zeros_like(b) for b in bs]; vb = [np.zeros_like(b) for b in bs]
    n = len(X); bsz = 256; t = 0
    for ep in range(epochs):
        perm = rng.permutation(n); tot = 0.0
        for s in range(0, n, bsz):
            idx = perm[s:s + bsz]; x, y, m = X[idx], Y[idx], M[idx]
            a1 = np.tanh(x @ Ws[0].T + bs[0]); a2 = np.tanh(a1 @ Ws[1].T + bs[1]); o = a2 @ Ws[2].T + bs[2]
            d = (o - y) * m; tot += float((d ** 2).sum()); d = d * (2.0 / max(1.0, m.sum()))
            gW2 = d.T @ a2; gb2 = d.sum(0)
            d2 = (d @ Ws[2]) * (1 - a2 ** 2); gW1 = d2.T @ a1; gb1 = d2.sum(0)
            d1 = (d2 @ Ws[1]) * (1 - a1 ** 2); gW0 = d1.T @ x; gb0 = d1.sum(0)
            t += 1
            for i, (gw, gb) in enumerate(((gW0, gb0), (gW1, gb1), (gW2, gb2))):
                for P, G, m_, v_ in ((Ws[i], gw, mW[i], vW[i]), (bs[i], gb, mb[i], vb[i])):
                    m_[:] = 0.9 * m_ + 0.1 * G; v_[:] = 0.999 * v_ + 0.001 * G * G
                    P -= lr * (m_ / (1 - 0.9 ** t)) / (np.sqrt(v_ / (1 - 0.999 ** t)) + 1e-8)
        if ep % 10 == 0 or ep == epochs - 1: print(f"epoch {ep} masked-mse {tot / max(1.0, M.sum()):.5f}")
    acts = [1, 1, 0]
    return [([list(map(float, row)) for row in Ws[i]], list(map(float, bs[i])), acts[i]) for i in range(3)]


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    d = sub.add_parser("distill"); d.add_argument("--out", required=True); d.add_argument("--emit-c")
    d.add_argument("--samples", type=int, default=60000); d.add_argument("--epochs", type=int, default=60)
    d.add_argument("--hidden", type=int, default=32); d.add_argument("--seed", type=int, default=1)
    i = sub.add_parser("info"); i.add_argument("file")
    a = ap.parse_args(argv)
    if a.cmd == "info":
        L = read_blob(open(a.file, "rb").read())
        print([(len(W[0]), len(W), act) for W, b, act in L]); return 0
    layers = distill(a.samples, a.epochs, a.hidden, a.seed)
    # quantise through the exact float32 path the C loader reads, so the reference and the C net are bit-identical inputs
    blob = write_blob(a.out, layers); layers = read_blob(blob)
    if a.emit_c: emit_c(a.emit_c, blob)
    rng = random.Random(99); agree = tot = 0
    for _ in range(3000):
        rs, kinds = random_state(rng); tch = teacher(rs, kinds)
        legal = [j for j, v in enumerate(tch) if v is not None]
        if not legal: continue
        o = forward(layers, E.build_observation(rs, kinds))
        agree += max(legal, key=lambda j: o[j]) == max(legal, key=lambda j: tch[j]); tot += 1
    print(f"wrote {len(blob)} bytes; held-out argmax agreement with teacher: {agree}/{tot} = {agree / tot:.3f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
