#!/usr/bin/env bash
# Regenerate core/runtime/ca_bundle_data.h from a real system CA bundle (S508f) -- Windows has no
# single-file CA bundle at a fixed path the way Linux's ca-certificates package does, so the
# Windows/mingw cross-build embeds a real, current CA bundle directly into the binary instead of
# reading one at runtime. PARENA's runtime (runtime/parena_runtime.h's own
# PARENA_TLS_CA_BUNDLE_EMBEDDED block) consumes the two symbols this generates
# (dw_ca_bundle_data/dw_ca_bundle_len). Checked in, not regenerated at build time -- same
# KARAMBIT/SPIDERBEETLE "generated file, checked in" convention core/card_rules.c already follows,
# so a build never silently ships a stale/different bundle than whatever was last reviewed here.
#
# Re-run this periodically (CA bundles rotate as certificate authorities are added/revoked) --
# not on every build.
set -euo pipefail
cd "$(dirname "$0")/.."
SRC="${CA_BUNDLE_SRC:-/etc/ssl/certs/ca-certificates.crt}"
OUT="core/runtime/ca_bundle_data.h"
test -f "$SRC" || { echo "gen_ca_bundle.sh: $SRC not found (Debian/Ubuntu ca-certificates package)"; exit 1; }
python3 - "$SRC" "$OUT" <<'PY'
import sys
src, out = sys.argv[1], sys.argv[2]
with open(src, "rb") as f:
    data = f.read()
with open(out, "w") as o:
    o.write("/* Generated by scripts/gen_ca_bundle.sh from a real system CA bundle -- do not edit by hand. */\n")
    o.write("#ifndef DW_CA_BUNDLE_DATA_H\n#define DW_CA_BUNDLE_DATA_H\n")
    o.write(f"static const unsigned char dw_ca_bundle_data[{len(data)+1}] = {{\n")
    for i in range(0, len(data), 20):
        o.write(",".join(str(b) for b in data[i:i+20]) + ",\n")
    o.write("0};\n")
    o.write(f"static const unsigned long dw_ca_bundle_len = {len(data)+1};\n")
    o.write("#endif\n")
print(f"gen_ca_bundle.sh: wrote {out} ({len(data)} real CA bundle bytes + NUL)")
PY
