/* cards_java -- prints android/.../CardText.java from core/card_text.c so the Java client's names/rule text can never drift
 * from the C table. Usage: (built and run by scripts/gen_rules.sh) cards_java > CardText.java */
#include <stdio.h>
#include "card_rules.h"
#include "card_text.h"

static void jstr(const char *s) { putchar('"'); for (; *s; s++) { if (*s == '"' || *s == '\\') putchar('\\'); putchar(*s); } putchar('"'); }

int main(void) {
    printf("package industrial.einhorn.deadweight;\n\n/** GENERATED by apps/tools/cards_java.c from core/card_text.c (scripts/gen_rules.sh): display names, rules text, kind and keyword\n *  names for the %d-card catalog. Do not edit by hand; every number and condition lives in PARENA's card_rules.prn. */\nfinal class CardText {\n    private CardText() {}\n\n", num_cards());
    printf("    private static final String[] NAME = {\n");
    for (int i = 0; i < num_cards(); i++) { printf("        "); jstr(dw_card_name(i)); printf("%s\n", i + 1 < num_cards() ? "," : ""); }
    printf("    };\n\n    private static final String[] TEXT = {\n");
    for (int i = 0; i < num_cards(); i++) { printf("        "); jstr(dw_card_text(i)); printf("%s\n", i + 1 < num_cards() ? "," : ""); }
    printf("    };\n\n");
    printf("    static String name(int id) { return id == -1 ? \"PASS\" : (id >= 0 && id < NAME.length) ? NAME[id] : \"?\"; }\n");
    printf("    static String text(int id) { return id >= 0 && id < TEXT.length ? TEXT[id] : \"\"; }\n");
    printf("    /** 0 Offense (Red), 1 Operations (Yellow), 2 Defense (Blue). */\n    static String kindName(int kind) { return kind == 0 ? \"Offense\" : kind == 1 ? \"Operations\" : kind == 2 ? \"Defense\" : \"?\"; }\n");
    printf("    /** Operations keyword name (card_keyword): \"\" for none. */\n    static String keywordName(int kw) {\n        switch (kw) { case 1: return \"Lock\"; case 2: return \"Sabotage\"; case 3: return \"Flank\"; case 4: return \"Scan\"; case 5: return \"Siphon\"; default: return \"\"; }\n    }\n}\n");
    return 0;
}
